name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build project
        run: cargo build --verbose

      - name: Check and Apply Code Formatting
        run: |
          cargo fmt -- --check || (
            echo "Applying cargo fmt to correct formatting issues"
            cargo fmt
          )

      - name: Run tests
        run: cargo test --verbose
